version: 2
updates:
  # Enable version updates for npm (JavaScript/TypeScript dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    assignees:
      - "Ahmed-Shehzad"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group related updates together to reduce PR noise
    groups:
      # Group Next.js and React ecosystem updates
      nextjs-react:
        patterns:
          - "next*"
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"

      # Group TypeScript and related tools
      typescript-tools:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
        update-types:
          - "minor"
          - "patch"

      # Group ESLint and Prettier tools
      linting-tools:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "prettier*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"

      # Group Tailwind CSS ecosystem
      tailwind-ecosystem:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"
          - "postcss*"
          - "autoprefixer"
        update-types:
          - "minor"
          - "patch"

      # Group testing tools
      testing-tools:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "jsdom"
          - "@testing-library/*"
        update-types:
          - "minor"
          - "patch"

      # Group build and development tools
      dev-tools:
        patterns:
          - "webpack*"
          - "vite*"
          - "@vitejs/*"
          - "esbuild"
          - "rollup*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    open-pull-requests-limit: 3
    assignees:
      - "Ahmed-Shehzad"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
    labels:
      - "github-actions"
      - "ci-cd"
      - "automated"
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
